name: clang-tools-7_windows-amd64

on:
  push:
    branches: [ gcc10-ub2004 ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: get llvm-project
      run: |
        choco install wget
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-7.1.0/llvm-7.1.0.src.tar.xz
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-7.1.0/cfe-7.1.0.src.tar.xz
        wget https://releases.llvm.org/7.1.0/clang-tools-extra-7.1.0.src.tar.xz
        $env:Path = "C:\Program Files\Git\usr\bin;$env:Path"
        tar.exe xf llvm-7.1.0.src.tar.xz
        tar.exe xf cfe-7.1.0.src.tar.xz --exclude=cfe-7.1.0.src/test/Driver/Inputs*
        tar.exe xf clang-tools-extra-7.1.0.src.tar.xz
        mkdir llvm-project-7.1.0
        mv llvm-7.1.0.src llvm-project-7.1.0/llvm
        mv cfe-7.1.0.src llvm-project-7.1.0/clang
        mv clang-tools-extra-7.1.0.src llvm-project-7.1.0/clang-tools-extra
    - name: make build directory
      run: mkdir -p llvm-project-7.1.0/build
    - name: cmake
      run: cd llvm-project-7.1.0/build && cmake ../llvm -Thost=x64 -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra" -DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_FLAGS="/MP" -DLLVM_USE_CRT_MINSIZEREL="MT"
    - name: build
      run: cd llvm-project-7.1.0/build && cmake --build . --config MinSizeRel --target clang-format clang-query clang-tidy
    - name: rename output binary
      run: |
        mv llvm-project-7.1.0\build\MinSizeRel\bin\clang-format.exe llvm-project-7.1.0\build\MinSizeRel\bin\clang-format-7_windows-amd64.exe
        mv llvm-project-7.1.0\build\MinSizeRel\bin\clang-query.exe llvm-project-7.1.0\build\MinSizeRel\bin\clang-query-7_windows-amd64.exe
        mv llvm-project-7.1.0\build\MinSizeRel\bin\clang-tidy.exe llvm-project-7.1.0\build\MinSizeRel\bin\clang-tidy-7_windows-amd64.exe
    - name: create and print sha512sum
      run: |
        $env:Path = "C:\Program Files\Git\usr\bin;$env:Path"
        cd llvm-project-7.1.0\build\MinSizeRel\bin
        sha512sum.exe clang-format-7_windows-amd64.exe > clang-format-7_windows-amd64.exe.sha512sum
        sha512sum.exe clang-query-7_windows-amd64.exe > clang-query-7_windows-amd64.exe.sha512sum
        sha512sum.exe clang-tidy-7_windows-amd64.exe > clang-tidy-7_windows-amd64.exe.sha512sum
        echo "Checksums are: "
        Get-Content -Path clang-format-7_windows-amd64.exe.sha512sum
        Get-Content -Path clang-query-7_windows-amd64.exe.sha512sum
        Get-Content -Path clang-tidy-7_windows-amd64.exe.sha512sum
    - name: upload release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "llvm-project-7.1.0/build/MinSizeRel/bin/clang-*-7_windows-amd64.exe*"
        draft: true
