name: clang-tools-static-amd64

on:
  push:
    branches: [ test ]

jobs:
  build:
    strategy:
      matrix:
        runner: [ ubuntu-20.04, macos-latest, windows-latest ]
    runs-on: ${{ matrix.runner }}
    steps:
    - name: test
      shell: bash
      run: |
        which sha512sum || true
